config/routes.rb
Medpasses::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :passbook, path: "passbook/api/v1" do
    constraints(pass_type_identifier: /([\w\d]\.?)+/) do
      post '/log' => 'passes#log'
      get '/passes/:pass_type_identifier/:serial_number' => 'passes#show'

      get '/devices/:device_library_identifier/registrations/:pass_type_identifier' => 'registrations#index'
      post '/devices/:device_library_identifier/registrations/:pass_type_identifier/:serial_number' => 'registrations#create'
      delete '/devices/:device_library_identifier/registrations/:pass_type_identifier/:serial_number' => 'registrations#destroy'
    end
  end

  resources :medications

  root :to => 'splash#index'
  match '/email_me' => 'application#email_me'
  match '/:page' => 'application#static'

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_one :pass, class_name: "Passbook::Pass", inverse_of: :medication
  belongs_to :user

  mount_uploader :thumbnail, MedicationImageUploader

  attr_accessible :active, :category, :directions, :dose, :name, :rationale, :units, :thumbnail

  after_create do |med|
    get_updated_thumbnail(med) unless med.thumbnail.current_path
  end

  after_save do
    self.pass.updated_at = self.updated_at
    self.pass.save!
    send_push_notification(self)
  end

  def get_updated_thumbnail(med)
      result = Pillboxr.with(image: true, ingredient: med.name, api_key: Mconf[Rails.env][:pillboxr_api_key])
      med.remote_thumbnail_url = result.pills.first.image_url unless result.record_count == 0
      med.save!
  end

  def send_push_notification(med)
    push_tokens = med.pass.registrations.map(&:push_token)

    if push_tokens.present?
      pusher = Grocer.pusher(certificate: Mconf[Rails.env][:push_cert_path],
                             passphrase: Mconf[Rails.env][:p12_cert_password],
                             gateway: 'gateway.push.apple.com')
      push_tokens.each do |token|
        notification = Grocer::PassbookNotification.new(device_token: token)
        pusher.push(notification)
      end
    end
  end

  handle_asynchronously :get_updated_thumbnail
  handle_asynchronously :send_push_notification
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_filter :authenticate_user!

  # GET /medications
  # GET /medications.json
  def index
    @medications = current_user.medications.all
    if current_user.sign_in_count < 2
      flash[:notice] = "You must access your medications using Safari on OS X or MobileSafari on your iPhone to be able to download passes."
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medications }
    end
  end

  # GET /medications/1
  # GET /medications/1.json
  def show
    @pass = Passbook::Pass.where(medication_id: Medication.find(params[:id])).first

    render :pkpass => @pass if @pass
  end

  # GET /medications/new
  # GET /medications/new.json
  def new
    @medication = Medication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medication }
    end
  end

  # GET /medications/1/edit
  def edit
    flash[:notice] = "Editing a medication will send a push notification to update the pass on your phone."
    @medication = Medication.find(params[:id])
  end

  # POST /medications
  # POST /medications.json
  def create
    @medication = Medication.new(params[:medication])
    @medication.user_id = current_user.id
    @medication.pass = @medication.build_pass(serial_number: SerialNumberGenerator.generate,
                                              auth_token: AuthTokenGenerator.token)

    respond_to do |format|
      if @medication.save!
        format.html { redirect_to medications_path, notice: 'Medication was successfully created.' }
        format.json { render json: @medication, status: :created, location: @medication }
      else
        format.html { render action: "new" }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medications/1
  # PUT /medications/1.json
  def update
    @medication = Medication.find(params[:id])

    respond_to do |format|
      if @medication.update_attributes(params[:medication])
        format.html { redirect_to medications_path, notice: 'Medication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medications/1
  # DELETE /medications/1.json
  def destroy
    @medication = Medication.find(params[:id])
    @medication.destroy

    respond_to do |format|
      format.html { redirect_to medications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.erb
<%= form_for(@medication) do |f| %>
  <% if @medication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</h2>

      <ul>
      <% @medication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dose %><br />
    <%= f.text_field :dose %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.text_field :units %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_field :directions %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
    <div class="field">
    <%= f.label :rationale %><br />
    <%= f.text_field :rationale %>
  </div>
  <div class="actions">
    <%= f.submit "Add Medication", class: "btn-large btn-primary span2" %>
  </div>
<% end %>

app/views/medications/edit.html.erb
<h1>Editing medication</h1>

<%= render 'form' %>

<%= link_to 'Show', @medication %> |
<%= link_to 'Back', medications_path %>

app/views/medications/index.html.erb
<div class="ac"><p><span>Medication images generously provided by the <a href="http://www.nlm.nih.gov">National Library of Medicine</a> at the <a href="http://www.nih.gov">National Institutes of Health</a> using the <a href="http://pillbox.nlm.nih.gov">Pillbox</a> API.  Many thanks to them.</a></span></p></div>
<h1>Listing Medications</h1>
<% if current_user.sign_in_count < 2 %>
<div class="alert alert-block">Please use Safari on OS X or MobileSafari on iPhone or you won't be able to download passes.<a href="#" id="close-button" class="close" data-dismiss="alert">×</a></div>
<% end %>

<div class="well hidden-phone visible-desktop">
<table class="table table-condensed table-hover hidden-phone visible-desktop">
  <tr>
    <th class="span2"></th>
    <th class="span4">Medication</th>
      <th class="span4">Directions</th>
      <th class="span4">Why?</th>
      <th class="span1"></th>
  </tr>

<% @medications.each do |medication| %>
  <tr>
    <td><%= image_tag(medication.thumbnail) %></td>
    <td><%= link_to medication.name.capitalize, edit_medication_path(medication) %><%= link_to image_tag('passbook_badge@2x.png', {class: "pull-right", width: 122, height: 40}), medication %><br/>
      <span><%= Integer(medication.dose) %><%= medication.units %></span>
    </td>
    <td><%= medication.directions %></td>
    <td>For your <%= medication.rationale %></td>
    <td><%= link_to "", medication, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-trash btn-large btn-danger" %></td>
  </tr>
<% end %>
</table>
</div>

<table class="table table-condensed table-hover visible-phone hidden-desktop">
  <tr>
    <th class="span8">Medication</th>
      <th class="span1"></th>
  </tr>

<% @medications.each do |medication| %>
  <tr>
    <td><%= link_to medication.name.capitalize, edit_medication_path(medication) %><%= link_to image_tag('passbook_badge@2x.png', {class: "pull-right", width: 122, height: 40}), medication %><br/>
      <span><%= Integer(medication.dose) %><%= medication.units %></span>
    </td>
    <td><%= link_to "", medication, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-trash btn-large btn-danger", style: "vertical-align:baseline;" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Medication', new_medication_path, :class => 'btn btn-primary' %>

app/views/medications/new.html.erb
<h1>New medication</h1>

<%= render 'form' %>

<%= link_to 'Back', medications_path %>